config/routes.rb
Rails.application.routes.draw do
  resources :line_items

  resources :glists

  resources :items

 root 'glists#index'

end

app/models/glist.rb
class Glist < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy
end

app/models/item.rb
class Item < ActiveRecord::Base
 has_many :line_items
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :item
	belongs_to :glist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/example_controller.rb
class ExampleController < ApplicationController
  def test
  	@current_time = Time.now
  end
end

app/controllers/glists_controller.rb
class GlistsController < ApplicationController
  before_action :set_glist, only: [:show, :edit, :update, :destroy]

  # GET /glists
  # GET /glists.json
  def index
    @glists = Glist.all
  end

  # GET /glists/1
  # GET /glists/1.json
  def show
    # need to get all line_items for this glist
    @all_line_items = @glist.line_items
  end

  # GET /glists/new
  def new
    @glist = Glist.new
  end

  # GET /glists/1/edit
  def edit
  end

  # POST /glists
  # POST /glists.json
  def create
    @glist = Glist.new(glist_params)

    respond_to do |format|
      if @glist.save
        format.html { redirect_to @glist, notice: 'Glist was successfully created.' }
        format.json { render :show, status: :created, location: @glist }
      else
        format.html { render :new }
        format.json { render json: @glist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /glists/1
  # PATCH/PUT /glists/1.json
  def update
    respond_to do |format|
      if @glist.update(glist_params)
        format.html { redirect_to @glist, notice: 'Glist was successfully updated.' }
        format.json { render :show, status: :ok, location: @glist }
      else
        format.html { render :edit }
        format.json { render json: @glist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /glists/1
  # DELETE /glists/1.json
  def destroy
    @glist.destroy
    respond_to do |format|
      format.html { redirect_to glists_url, notice: 'Glist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_glist
      @glist = Glist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def glist_params
      params.require(:glist).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :set_item, only: [:show, :edit, :update, :destroy]
	def index
		@items = Item.all
	end

  # GET /items/1
	def show
		
	end

  # GET /items/new
	def new
		@item = Item.new
	end

	# GET /items/1/edit
  def edit
  end

  # POST /items
	def create
		@item = Item.new(item_params)
		if @item.save
			redirect_to items_url, notice: 'Item Succesfully saved'
		else
			render :new
		end
	end

	# PATCH/PUT /items/1
	def update
		if @item.update(item_params)
			redirect_to items_url, notice: 'Item was updated.'
		else
			render :edit
		end
	end

	def destroy
		@item.destroy
		redirect_to items_url, notice: 'Item deleted'
	end



	private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
	  def item_params
	  	params.require(:item).permit(:name)
	  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show

  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
    @line_item.glist_id = 1 # TODO: this should come from a parameter indicating which
      # glist id should be used.
  end
  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.glist, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to @line_item.glist, notice: 'Line item was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:glist_id, :item_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/example_helper.rb
module ExampleHelper
end

app/helpers/glists_helper.rb
module GlistsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/example/_footer.html.erb
<hr><p>Copyright <%= "#{start_year} - " if defined? start_year %>
<%= Date.today.year %> grocerylist.com</p>

app/views/example/test.html.erb
<p>The current time is <%= @current_time %></p>
<%= render partial: "footer", locals: { start_year: "2001" } %>

app/views/glists/_form.html.erb
<%= form_for(@glist) do |f| %>
  <% if @glist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@glist.errors.count, "error") %> prohibited this glist from being saved:</h2>

      <ul>
      <% @glist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/glists/edit.html.erb
<h1>Editing glist</h1>

<%= render 'form' %>

<%= link_to 'Show', @glist %> |
<%= link_to 'Back', glists_path %>

app/views/glists/index.html.erb
<!-- start glists/index.html.erb -->
<h1>All Your Grocery Lists</h1>
<%= link_to '<i class="fi-plus"></i> New List'.html_safe, new_item_path, class: "button" %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @glists.each do |glist| %>
      <tr>
        <td><%= link_to glist.name, glist %></td>
        <td> | </td>
        <td><%= link_to '<i class="fi-x"></i>'.html_safe, glist, method: :delete, data: { confirm: "Remove List\n\n#{glist.name}\n\nAre you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<i class="fi-plus"></i> New List'.html_safe, new_glist_path, class: "button radius"%>
<!-- end glists/index.html.erb -->

app/views/glists/new.html.erb
<h1>New glist</h1>

<%= render 'form' %>

<%= link_to 'Back', glists_path %>

app/views/glists/show.html.erb
<p>
  <strong>List Name:</strong>
<%= link_to @glist.name, edit_glist_path(@glist) %>
</p>
<%= link_to '<i class="fi-plus"></i> Add Item to List'.html_safe, new_line_item_path, class: "button" %>
<table>
  <thead>
    <tr>
      <th>Item Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @all_line_items.each do |line_item| %>
      <tr>
        <td><%= link_to line_item.item.name, edit_line_item_path(line_item) %></td>
        <td> | </td>

        <td><%= link_to '<i class="fi-x"></i>'.html_safe, line_item, method: :delete, data: { confirm: "Remove #{line_item.item.name}\n\nfrom the list: #{@glist.name}\n\nAre you sure?" } %></td>
      </tr>
    <% end %>
      </tbody>
</table>
<br>
<%= link_to '<i class="fi-plus"></i> Add Item to List'.html_safe, new_line_item_path, class: "button" %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back to Items', items_path, class: "button" %>

app/views/items/index.html.erb
<h1>List of Grocery Items</h1>
<p><%= link_to '<i class="fi-plus"></i> New Item'.html_safe, new_item_path, class: "button" %></p> 
<table>
  <thead>
    <tr>
      <th>Item Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr><!--
        <td><%= item.name %></td>
        <td><%= link_to item.name, item %></td>-->
        <td><%= link_to item.name, edit_item_path(item) %></td>
        <td> | </td>
        <td><%= link_to '<i class="fi-x"></i>'.html_safe, item, method: :delete, data: { confirm: "Remove #{item.name}\n\nAre you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<i class="fi-plus"></i> New Item'.html_safe, new_item_path, class: "button" %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path, class: "button" %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<%= link_to 'Back to Items', items_path %>
</p>
<br>
<table>
  <thead>
    <tr>
      <th>Item Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @item.name %></td>
        <td><%= link_to 'Edit', edit_item_path(@item) %> |</td>
        <td><%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Grocery List" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<h1>Grocerylist.com</h1>
<div class="menu">
  <%= link_to '<i class="fi-list"></i> Your Lists'.html_safe, glists_path %> |
  <%= link_to '<i class="fi-thumbnails"></i> All Items'.html_safe, items_path %>
</div>


<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

<!-- start yield -->
    <%= yield %>
<!-- end   yield -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'List Name' %><br>
    <%= f.collection_select :glist_id, Glist.all, :id, :name %>
    
  </div>
  <div class="field">
    <%= f.label 'Grocery item' %><br>
    <%= f.collection_select :item_id, Item.all, :id, :name %>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Glist</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.glist.name %></td>
        <td><%= line_item.item.name %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List Name:</strong>
  <%= @line_item.glist.name %>
</p>

<p>
  <strong>Item Name:</strong>
  <%= @line_item.item.name %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>